### PR TITLE
Add many-to-many relationships

### PR DESCRIPTION
**Pull request by Gegardus**
In this part of the project were: 

- Added join tables to implement some many-to-many relationships 
- Performed complex queries to answer questions.

### CODE REVIEW

**Review by emmanuellekamwa — APPROVED** [review]
**STATUS: APPROVED 🍾🎉✔**
Hello @Gegardus 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gegardus** [comment]
Hi @emmanuellekamwa 

I don't know why, but I can't submit this project. In my Dashboard, in the progress section, the status "review pending" is still set. I don't know all the technology, but maybe you forgot something, because of which I can't submit the project now... Please, answer me.

Best regards

**Comment by descholar-ceo** [comment]
> Hi @emmanuellekamwa
> 
> I don't know why, but I can't submit this project. In my Dashboard, in the progress section, the status "review pending" is still set. I don't know all the technology, but maybe you forgot something, because of which I can't submit the project now... Please, answer me.
> 
> Best regards

Hello @Gegardus 
I am re-approving your project for the sake of you to submit, kindly let me know how it came out by commenting on this thread.

**Review by descholar-ceo — APPROVED** [review]

**Comment by emmanuellekamwa** [comment]
Hello. I am so sorry about it. I have already approved your project since
but I forgot to submit. Sorry for the inconvenience

**Comment by Gegardus** [comment]
Thank you @descholar-ceo 
Thank you @emmanuellekamwa

**Pull request merged**
